
camera:
  camId: 4

audio:
  activationWord: "glasses"
  device: "default"

openai:
  keyFile: "./oai_key"
  model: "gpt-4o-mini-audio-preview"
  transcribeModel: "gpt-4o-mini-transcribe"
  imageModel: "gpt-4.1-mini"
  ttsModel: "gpt-4o-mini-tts"
  voice: "nova"
