string(TOUPPER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_UPPER)

set(libbase64_PREFIX ${CMAKE_CURRENT_BINARY_DIR}/libbase64)

ExternalProject_Add(turbobase64
  PREFIX ${libbase64_PREFIX}
  GIT_REPOSITORY https://github.com/powturbo/Turbo-Base64
  GIT_TAG 2023.08
  GIT_SUBMODULES_RECURSE ON
  GIT_REMOTE_UPDATE_STRATEGY CHECKOUT
  INSTALL_COMMAND ""
  LIST_SEPARATOR |
  CMAKE_CACHE_ARGS
        "-DCMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_EXE_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_EXE_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_SHARED_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_SHARED_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}"
	      "-DCMAKE_TOOLCHAIN_FILE:PATH=${CMAKE_TOOLCHAIN_FILE}"
        "-DBUILD_APP:BOOL=OFF"
        "-DBUILD_SHARED_LIBS:BOOL=OFF"
)

add_library(libbase64 INTERFACE)
add_dependencies(libbase64 turbobase64)

target_include_directories(libbase64 INTERFACE ${libbase64_PREFIX}/src/turbobase64/)
target_link_libraries(libbase64 INTERFACE "${libbase64_PREFIX}/src/turbobase64-build/libbase64.a")
