string(TOUPPER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_UPPER)

set(libsdl_PREFIX ${CMAKE_CURRENT_BINARY_DIR}/libsdl)
#set(libsdl_OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/libsdl-out)


set(sdl_PREFIX ${CMAKE_CURRENT_BINARY_DIR}/sdl)


ExternalProject_Add(sdl
  PREFIX ${sdl_PREFIX}
  GIT_REPOSITORY https://github.com/libsdl-org/SDL
  GIT_TAG release-2.32.8
  GIT_SUBMODULES_RECURSE ON
  GIT_REMOTE_UPDATE_STRATEGY CHECKOUT
  INSTALL_COMMAND ""
  BUILD_IN_SOURCE OFF
  CMAKE_CACHE_ARGS
        "-DCMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_EXE_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_EXE_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_SHARED_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_SHARED_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_BUILD_TYPE:STRING=Release"
	      "-DCMAKE_TOOLCHAIN_FILE:PATH=${CMAKE_TOOLCHAIN_FILE}"
        "-DSDL_BUILD_SHARED_LIBS:BOOL=OFF"
        "-DBUILD_SHARED_LIBS:BOOL=OFF"
        "-DSDL_TEST:BOOL=OFF"
)



ExternalProject_Add(sdlmixer
  PREFIX ${libsdl_PREFIX}
  GIT_REPOSITORY https://github.com/libsdl-org/SDL_mixer
  GIT_TAG release-2.8.1
  GIT_SUBMODULES_RECURSE ON
  GIT_REMOTE_UPDATE_STRATEGY CHECKOUT
  INSTALL_COMMAND ""
  BUILD_IN_SOURCE OFF
  DEPENDS sdl
  CMAKE_CACHE_ARGS
        "-DCMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_EXE_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_EXE_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_SHARED_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_SHARED_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_BUILD_TYPE:STRING=Release"
	      "-DCMAKE_TOOLCHAIN_FILE:PATH=${CMAKE_TOOLCHAIN_FILE}"
        "-DSDLMIXER_BUILD_SHARED_LIBS:BOOL=OFF"
        "-DBUILD_SHARED_LIBS:BOOL=OFF"
        "-DSDL2MIXER_OPUS:BOOL=OFF"
        "-DSDL2MIXER_MOD:BOOL=OFF"
        "-DSDL2MIXER_MIDI:BOOL=OFF"
        "-DSDL2MIXER_WAVPACK:BOOL=OFF"
        "-DSDL2_LIBRARY:STRING=${sdl_PREFIX}/src/sdl-build/libSDL2.a"
        "-DSDL2_INCLUDE_DIR:STRING=${sdl_PREFIX}/src/sdl/include"
        "-DSDL2MIXER_DEPS_SHARED:BOOL=OFF"
        "-DSDL2MIXER_SAMPLES:BOOL=OFF"
)

add_library(libsdl INTERFACE)
add_dependencies(libsdl sdlmixer)

target_include_directories(libsdl INTERFACE ${libsdl_PREFIX}/src/sdlmixer/include/)
target_include_directories(libsdl INTERFACE ${sdl_PREFIX}/src/sdl/include/)
target_link_libraries(libsdl INTERFACE "${libsdl_PREFIX}/src/sdlmixer-build/libSDL2_mixer.a")
