string(TOUPPER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_UPPER)

set(libsdl_PREFIX ${CMAKE_CURRENT_BINARY_DIR}/libsdl)
set(libsdl_OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/libsdl-out)
set(libsdl_BINARY ${CMAKE_CURRENT_BINARY_DIR}/libsdl-bin)

ExternalProject_Add(sdlmixer
  PREFIX ${libsdl_PREFIX}
  GIT_REPOSITORY https://github.com/libsdl-org/SDL_mixer
  GIT_TAG release-2.8.1
  GIT_SUBMODULES_RECURSE ON
  GIT_REMOTE_UPDATE_STRATEGY CHECKOUT
  INSTALL_COMMAND ""
  BINARY_DIR ${libsdl_BINARY}
  SOURCE_DIR ${libsdl_OUTPUT}
  LIST_SEPARATOR |
  CMAKE_CACHE_ARGS
        "-DCMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_EXE_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_EXE_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_SHARED_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_SHARED_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}"
	      "-DCMAKE_TOOLCHAIN_FILE:PATH=${CMAKE_TOOLCHAIN_FILE}"
        "-DSDLMIXER_BUILD_SHARED_LIBS:BOOL=OFF"
        "-DBUILD_SHARED_LIBS:BOOL=OFF"
)

add_library(libsdl INTERFACE)
add_dependencies(libsdl sdlmixer)

target_include_directories(libsdl INTERFACE ${libsdl_OUTPUT}/include/)
#target_link_libraries(libsdl INTERFACE "${libsdl_OUTPUT}/libtb64.a")
