string(TOUPPER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_UPPER)

set(uni_PREFIX ${CMAKE_CURRENT_BINARY_DIR}/uni-algo)

ExternalProject_Add(unialgo
  PREFIX ${uni_PREFIX}
  GIT_REPOSITORY https://github.com/uni-algo/uni-algo
  GIT_TAG v1.2.0
  GIT_SUBMODULES_RECURSE ON
  GIT_REMOTE_UPDATE_STRATEGY CHECKOUT
  INSTALL_COMMAND ""
  LIST_SEPARATOR |
  CMAKE_CACHE_ARGS
        "-DCMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_EXE_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_EXE_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_SHARED_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_SHARED_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
        "-DCMAKE_BUILD_TYPE:STRING=Release"
	      "-DCMAKE_TOOLCHAIN_FILE:PATH=${CMAKE_TOOLCHAIN_FILE}"
        "-DBUILD_SHARED_LIBS:BOOL=OFF"
        "-DUNI_ALGO_HEADER_ONLY:BOOL=OFF"
)

add_library(uni-algo INTERFACE)
add_dependencies(uni-algo unialgo)

target_include_directories(uni-algo INTERFACE ${uni_PREFIX}/src/unialgo/include)
target_link_libraries(uni-algo INTERFACE "${uni_PREFIX}/src/unialgo-build/libuni-algo.a")
