

# settings specific to camera handling
camera:
  # camera id for cv::VideoCapture constructor (probably '0' if only one camera is present)
  camId: 0

# settings for audio capture/playback
audio:

  #speech must start with one of this words to be processed

  #if speech starts with this it will be send to openai for processing
  aiActivationWord: "chat"

  #if speech starts with this the string will be sent to the image thread to control modes
  cmdActivationWord: "glass"

  #set either to false to perform online speech recognition before final processing
  cmdLocalSpeechDetectOnly: true
  aiLocalSpeechDetectOnly: true

  #microphone device to use
  device: "default"

  echoSpeech: false

#config for local speech detection
whisper:
  #model for detecting the presence of speech in audio segment
  vadModel: "/home/orangepi/ggml-silero-v5.1.2.bin"
  vadThreshold: 0.8

  #model for local speech to text conversion (used for activation work detection at least)
  model: "/home/orangepi/ggml-base.en.bin"
  maxThreads: 3


#settings for openai integration
openai:
  #full path to file containing the openai api key
  keyFile: "/home/orangepi/oai_key"

  #for different types of requests different openai models can be used a various speed and price options
  #Details of models available can be found here: https://platform.openai.com/docs/models

  #ai model to use for text to audio api requests (must support audio output)
  model: "gpt-4o-mini-audio-preview"
  #ai model to use for speech to text requests (must support transcribe operation)
  transcribeModel: "gpt-4o-mini-transcribe"
  #ai model to use for image analysing (will not also support audio output currently)
  imageModel: "gpt-4.1-mini"
  #ai moddel to use for text to speech requests
  ttsModel: "gpt-4o-mini-tts"

  #openai voice to use for speech output (openai supports several voices: https://platform.openai.com/docs/guides/text-to-speech)
  voice: "nova"

  #if these words appear in the AI request text, the current image frame will be included
  imageInclusionKeywords:
    - "image" #e.g. describe this image
    - "seeing" #e.g. describe what I am seeing
    - "photo" #e.g. what is in this photo?
